import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { ToastContainer} from 'react-toastify';
import { ProductContextProvider } from "@/context/Product.Context";
  

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      
    <body>
    <ClerkProvider>
      
      <html lang="en">
        <body> 
          <ProductContextProvider>
          <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Navbar />
          <main className="min-h-screen ">
            {children}
            <ToastContainer />
          </main>
          </ThemeProvider>
          </ProductContextProvider>
        </body>
      </html>
    
    </ClerkProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
